### ISSUE TITLE
Meetup API deprecated - tutorial needs updating to use OAuth

### ISSUE THREAD

**Issue by RCheesley** [chaoss/grimoirelab-tutorial#114]
In this file: gelk/meetup.md we make reference to the Meetup API and link to the appropriate page (https://secure.meetup.com/es-ES/meetup_api/key/) to get the API key.

Since August 2019, the Meetup API has been deprecated, now you need a Pro account, and need to use OAuth - see https://www.meetup.com/meetup_api/auth/ for developer docs.

The documentation in this tutorial (and possibly elsewhere) should be updated to reflect this.

**Comment by valeriocos** [comment]
Hi @RCheesley , in order to get an Aouth token please use this script: https://gist.github.com/valeriocos/e16424bc7dc0f2d6dd8bb9295c6f9a4b

We will update the documentation soon.

**Comment by valeriocos** [comment]
Thanks @RCheesley for the PR!
