### ISSUE TITLE
Broken link in Micro-mordred tutorial

### ISSUE THREAD

**Issue by sp35** [chaoss/grimoirelab-tutorial#125]
https://chaoss.github.io/grimoirelab-tutorial/sirmordred/micro-mordred.html#what-is-mordred
```
Mordred is the tool used to orchestrate the execution of the GrimoireLab platform, via a configuration file. We can find more details about the sections in the configuration file here.
```
The link at the word 'here' doesn't work.

**Comment by valeriocos** [comment]
Good catch, thanks @sp35 ! Can you submit a PR?

**Comment by sp35** [comment]
@valeriocos I guess its link to```setup.cfg```

**Comment by valeriocos** [comment]
Sorry for the late reply @sp35 . Yes, the reference should be https://github.com/chaoss/grimoirelab-sirmordred#setupcfg
