### ISSUE TITLE
Clairity on Mordred configuraiton

### ISSUE THREAD

**Issue by Nolski** [chaoss/grimoirelab-tutorial#132]
# Overview

The current GrimoireLab documentation provides some example of how to configure Mordred for certain data backends and tells the reader to reference Perceval for further information. The issue is, it's unclear the json format each backend requires. 

## Further Details

For instance, I'm unsure if the `discourse` backend requires an array of URLs, or a single URL or something different.  

I've tried both and ran the docker-compose service `mordred` but have yet to see any discourse data show up in kibana, even though I see plenty of json output when running `mordred discourse <URL>` in the same environment. An example of my projects.json is below

```json
{
    "fossrit": {
        "meta": {
            "title": "FOSS@RIT"
        },
        "git": [
            "https://github.com/FOSSRIT/hfoss-wiki.git"
        ],
        "github": [
            "https://github.com/FOSSRIT/hfoss-wiki"
        ],
        "discourse": "https://fossrit.community"
    }
}
```

**Comment by vchrombie** [comment]
Hi @Nolski, thanks for showing your interest in GrimoireLab.

> The issue is, it's unclear the json format each backend requires.

Sorry for the confusion, but all the backends follow the same format. The URLs should be given as an array.

projects.json
```
{
    "fossrit": {
        "meta": {
            "title": "FOSS@RIT"
        },
        "git": [
            "https://github.com/FOSSRIT/hfoss-wiki.git"
        ],
        "github": [
            "https://github.com/FOSSRIT/hfoss-wiki"
        ],
        "discourse": [
            "https://fossrit.community"
        ]
    }
}
```
You can also get the information in the [supported-datasources section](https://github.com/chaoss/grimoirelab-sirmordred/#supported-data-sources-) from the [sirmordred](https://github.com/chaoss/grimoirelab-sirmordred) repository.

> I've tried both and ran the docker-compose service mordred but have yet to see any discourse data show up in kibana, even though I see plenty of json output when running mordred discourse <URL> in the same environment.

It would be great if we can have a look at the `setup.cfg` configurations too. Ideally, it should be something similar to this.

setup.cfg
```
[discourse]
raw_index = discourse_raw
enriched_index = discourse_enriched
no-archive = true (suggested)
```
You can also refer, [discourse](https://github.com/chaoss/grimoirelab-sirmordred/#discourse-) configurations.

Hope this helps, let us know how it goes for you.
Thanks.

**Comment by zhquan** [comment]
Hi @Nolski,

Just completing @vchrombie's comment.

On the [readme](https://github.com/chaoss/grimoirelab-tutorial) If you go on the second paragraph and click on [data sources](https://gitlab.com/Bitergia/c/FAQ/tree/master/sources#supported-data-sources) then search for [confluence](https://gitlab.com/Bitergia/c/FAQ/tree/master/sources#confluence) the format is 
```
{
    "Alice": {
        "confluence": [
            "https://wiki.myproject.org"
        ],

```

> I've tried both and ran the docker-compose service mordred but have yet to see any discourse data show up in kibana

You will see the data on the kibana when the enrichment phase is finished.

```
...
2021-01-11 xx:xx:xx,xxx - sirmordred.task_enrich - INFO - [discourse] enrichment phase finished in x:xx:xx
...
```

And very important you must activate `panels` on the section `phases` in your `setup.cfg` to import the index patterns, visualizations, and dashboards.

```
...
[phases]
collection = true
identities = true
enrichment = true
panels = true
...
```


I hope it helps you.

Best,
Quan

**Comment by Nolski** [comment]
Hi @zhquan and @vchrombie 

Thanks for the quick response! It looks like it was both the formatting of my `projects.json` as well as missing a configuration for discourse in my setup.cfg. I submitted a PR to update the setup.cfg included in `default-grimoirelab-settings` which is referenced above in case y'all might find that useful.

I'll close this issue now as my question is answered :)
