### ISSUE TITLE
Remove "Presentation" from the docs

### ISSUE THREAD

**Issue by SteveKola** [chaoss/grimoirelab-tutorial#134]
I noticed that the Presentation page and the Introduction page contain the same information.

Is there a reason for this duplication? 
If there's none, can I have it removed?

**Comment by vchrombie** [comment]
Hi @SteveKola, thanks for finding this out and opening the issue.

I can see the duplication and I think it is safe to remove that. Let me know if you are interested in opening a PR for it. You just need to change an entry here, https://github.com/chaoss/grimoirelab-tutorial/blob/master/_data/sidebars/home_sidebar.yml.

Please let us know if you need any help.
Thanks.

**Comment by SteveKola** [comment]
Hello @vchrombie, 

I'd be happy to create a PR for it. This would be my first PR here so that's something 😄 

Thank you.

**Comment by vchrombie** [comment]
Fixed by https://github.com/chaoss/grimoirelab-tutorial/pull/136

**Comment by vchrombie** [comment]
@SteveKola can you close the issue?
