### ISSUE TITLE
Could not extract data from Gerrit

### ISSUE THREAD

**Issue by isikozsoy** [chaoss/grimoirelab-tutorial#154]
I want to extract code reviews it does not matter where I extract since it will be used for test purposes.
I used those attributes hostname': 'gerrit.opnfv.org', 'user': 'user' as you examplified
however I got the following error user@gerrit.opnfv.org: Permission denied (publickey).
What should I do? Thanks for your time!

**Comment by zhquan** [comment]
Hi @isikozsoy 

You have to add your public key to gerrit.opnfv.org.

Steps:
1. Create an account if you don't have it
2. Go to `settings` -> `Profile`: make sure that you have a `username`
3. Go to `settings` -> `SSH Keys`: add your public key

The param `user` is your `username` and that is why you got the error `user@gerrit.opnfv.org: Permission denied (publickey)`

I hope it helps you

Best,
Quan

**Comment by isikozsoy** [comment]
Thanks Quan! I found my mistake. Thanks a lot for your time.
Best,
Işık
