### ISSUE TITLE
Unable to access enriched information .

### ISSUE THREAD

**Issue by SourabhSaraswat-191939** [chaoss/grimoirelab-tutorial#155]
this is the command which i used in Docker CLI . 
$ p2o.py --enrich --index git_raw --index-enrich git \\
  -e http://localhost:9200 --no_inc --debug \\
  git https://github.com/grimoirelab/GrimoireELK.git

it works fine and showing "Total items enriched 2922" and other process summary . But when i am trying to visit it from "http://localhost:9200/git_raw?pretty=true" or "http://localhost:9200/git_raw?pretty=true" or "http://localhost:9200" nothing is working out of this . I am following Tutorial "https://chaoss.github.io/grimoirelab-tutorial/gelk/simple.html" .

I used "grimoirelab/full" Docker Image for Grimoirelab setup .

**Comment by vchrombie** [comment]
Hi @SourabhSaraswat-191939, we need some logs to tell the exact issue what could be wrong with the elasticsearch.

In any case, the docker image is quite outdated. It would be great if you can use the [docker-compose](https://github.com/chaoss/grimoirelab/tree/master/docker-compose) method. Also, the p2o.py script is not maintained anymore, you can run [mordred](https://github.com/chaoss/grimoirelab-sirmordred). You can even execute [micro-mordred](https://github.com/chaoss/grimoirelab-sirmordred#micro-mordred-) which is a simplified version of Mordred.

**Comment by SourabhSaraswat-191939** [comment]
![Screenshot 1942-12-29 at 8 33 49 PM](https://user-images.githubusercontent.com/60272417/111874507-ae3c2900-89bb-11eb-985e-44017d78849a.png)
This is the logs after using that command again .

**Comment by SourabhSaraswat-191939** [comment]
I think this Docker image is Up To Date as i pulled this image some days before .

**Comment by SourabhSaraswat-191939** [comment]
Okay, i will go through docker-compose and others as you mentioned . 👍
