### ISSUE TITLE
Help required for Microtask 3 under "Reporting of CHAOSS Metrics"

### ISSUE THREAD

**Issue by tezansahu** [chaoss/grimoirelab-tutorial#17]
Hi,

I have started learning about the GrimoireLab and its functionalities. I am also trying to do a few Microtasks under Reporting of CHAOSS Metrics wherein I need your help.

In Microtask 3, I am able to generate a data table containing pull requests and issues of different Grimoirelab repos for the last 3 months and also another data table having commits according to different repos. But since they belong to different indexes (PRs and Issue come from Github while Commits come from Git), I am unable to understand how to merge them into a single table. Please let me know how to go about this.

I am also attaching the data tables that I have produced so far for your referral.

Regards,
Tezan Sahu

![microtask 3 progress](https://user-images.githubusercontent.com/31898274/36976905-34b7dc78-20a5-11e8-9ee7-b9780baf6e76.png)
![microtask 3 progress -2](https://user-images.githubusercontent.com/31898274/36976906-34e06558-20a5-11e8-9e9d-14c443782cb6.png)

**Comment by aswanipranjal** [comment]
Hey @tezansahu, this thread may be able to help you: [https://discuss.elastic.co/t/use-multiple-index-in-a-chart/44653](https://discuss.elastic.co/t/use-multiple-index-in-a-chart/44653). If you only have 2 indices with names `git` and `github_issues`, then you can use the wildcard index `git*` to get them both at the same time.

**Comment by tezansahu** [comment]
Thank you. Will try doing so.

**Comment by karansingh1559** [comment]
@aswanipranjal can you please help with me issue #18 :smile: ?
