### ISSUE TITLE
Error on running the mordred command

### ISSUE THREAD

**Issue by karansingh1559** [chaoss/grimoirelab-tutorial#18]
When I run 
`mordred -c mordred-grimoirelab.cfg
`, I get the error:
> Traceback (most recent call last):
  File "/usr/local/bin/mordred", line 145, in <module>
    logger = setup_logs(logs_dir, debug_mode, log_file_handler, log_max_bytes, log_backup_count)
  File "/usr/local/bin/mordred", line 70, in setup_logs
    fh = log_file_handler(fh_filepath, **log_file_handler_kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1008, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/logs/all.log'

How do I resolve this?

**Comment by karansingh1559** [comment]
@jgbarah I've not been able to proceed any further. Could you please help me on this ? :D

**Comment by aswanipranjal** [comment]
@karansingh1559, I think you'll have to create a `tmp/logs` directory in your root folder. The logging module saves the logging data in a file in that tmp/logs directory known as `all.log`. Can you please try to create the required directory?

**Comment by karansingh1559** [comment]
Okay that worked. But it now says that 'access denied for "jgb @localhost". Looking at the config file, in the sorting hat section, I guess I need to change these parameters. Is that the case?

**Comment by jgbarah** [comment]
Thanks a lot, @aswanipranjal, for your help, and @karansingh1559, for your report. Yes, that is an example, you should change it to your own credentials. Let us know if it doesn't work when you try that way.

I've added some more text to the description in the tutorial, trying to clarify this part. I'm closing this for now, but please feel free to reopen if you think the text in the tutorial is not good enough.
