### ISSUE TITLE
Port the developer installation method to the new tutorial

### ISSUE THREAD

**Issue by vchrombie** [chaoss/grimoirelab-tutorial#183]
The main aim of this issue is to port the developer installation of GrimoireLab to the new tutorial.
https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md

Ideally the _dev-setup.md_ file should go to https://github.com/chaoss/grimoirelab-tutorial/tree/master/docs/getting-started and should have the [Getting-Started content](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#getting-started-), and the [Troubleshooting content](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#troubleshooting-) can go to https://github.com/chaoss/grimoirelab-tutorial/blob/master/docs/getting-started/troubleshooting.md file.

**Comment by Sukriti-sood** [comment]
Hi @vchrombie I want to work on this issue, but I am not clear on the purpose. Can you please clarify?

**Comment by vchrombie** [comment]
Hi @Sukriti-sood, thanks for showing interest in CHAOSS and GrimoireLab.

Initially we started off with adding the instructions to setup the developer environment for grimoirelab in the sirmordred repository. We didn't have a proper layout for tutorial back then and we felt sirmordred repo is the right place.
https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md

But, now we have a ~proper~ good tutorial (still needs improvements), I was thinking if we can port the instructions to the current tutorial.

> Ideally the _dev-setup.md_ file should go to https://github.com/chaoss/grimoirelab-tutorial/tree/master/docs/getting-started and should have the [Getting-Started content](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#getting-started-), and the [Troubleshooting content](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#troubleshooting-) can go to https://github.com/chaoss/grimoirelab-tutorial/blob/master/docs/getting-started/troubleshooting.md file.

This is the aim of this issue, please let me know if you need more help.
