### ISSUE TITLE
Questions about the idea: Reporting of CHAOSS Mertics

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/grimoirelab-tutorial#19]
I had some questions about the project Reporting of CHAOSS metrics:

1) To extend the functionality of Manuscripts, we will need to add code to calculate the Metrics listed down at https://github.com/chaoss/metrics, right? 
If so, how do you suggest that the user demographics be collected and monitored?

2) In the 3rd Microtask for the project, it is said that: **Produce a listing of repositories, as a table and as CSV file, with the number of commits authored, issues opened, and pull requests opened, during the last three months, ordered by the total number (commits plus issues plus pull requests).**
Does that mean all the public repositories created in the last 3 months? Or does that mean that all the repositories should be listed according to the **number of commits authored + pull requests made + issues opened made in the last 3 months**?
If the answer is the latter one: then how many repositories should be listed out?

**Comment by jgbarah** [comment]
Thanks for your question. I'm answering it in chaoss/grimoirelab#70, together with all the comments on this GSoC idea.
