### ISSUE TITLE
Update invalid urls in `/components/workflow.md`

### ISSUE THREAD

**Issue by TieWay59** [chaoss/grimoirelab-tutorial#204]
I found a list of invalid URLs. Two of them are related to `basics/scenarios` which is placed in the same directory of `workflow.md` now. 
But I didn't find `/manuscripts/first` in the current branch.
If someone can make the right URLs clear to me, I can PR and fix it.

https://github.com/chaoss/grimoirelab-tutorial/blob/654bd0563dd45c9f76fb8486541a614e66fd28e8/docs/components/workflow.md#L41

https://github.com/chaoss/grimoirelab-tutorial/blob/654bd0563dd45c9f76fb8486541a614e66fd28e8/docs/components/workflow.md#L60

https://github.com/chaoss/grimoirelab-tutorial/blob/654bd0563dd45c9f76fb8486541a614e66fd28e8/docs/components/workflow.md#L63

**Comment by vchrombie** [comment]
Hi @TieWay59, thanks for opening the issue.

We usually point towards the individual tool's documentation in the Workflow page but not every tool has its own readthedocs page yet. I would suggest redirecting them to the README of the tool to avoid much confusion.

> https://github.com/chaoss/grimoirelab-tutorial/blob/654bd0563dd45c9f76fb8486541a614e66fd28e8/docs/components/workflow.md#L41
 
https://github.com/chaoss/grimoirelab-kingarthur

> https://github.com/chaoss/grimoirelab-tutorial/blob/654bd0563dd45c9f76fb8486541a614e66fd28e8/docs/components/workflow.md#L60

https://github.com/chaoss/grimoirelab-manuscripts
 
> https://github.com/chaoss/grimoirelab-tutorial/blob/654bd0563dd45c9f76fb8486541a614e66fd28e8/docs/components/workflow.md#L63

https://github.com/chaoss/grimoirelab-sirmordred

Please let me know if you need any help. Feel free to tag me to review the PRs.
