### ISSUE TITLE
Remove "$" from terminal commands so they can be copied more easily

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab-tutorial#214]
**Problem:** When I copy a terminal command from our tutorial, it also copies the "$" sign which is not part of the command as it needs to be entered in the terminal.

**Proposed Solution:** remove the "$" sign from all commands in the tutorial.

The page I experienced this problem on is the installation guide at: https://chaoss.github.io/grimoirelab-tutorial/docs/getting-started/setup/

**Comment by retry19** [comment]
can you add hacktoberfest's label on this issue?

**Comment by GeorgLink** [comment]
Thanks for the idea @retry19 ! Label was added.

**Comment by retry19** [comment]
Thanks, can I work on this?

**Comment by GeorgLink** [comment]
Yes, go for it :-)

**Comment by vchrombie** [comment]
> Thanks, can I work on this?

Yes please feel free to pick it @retry19. Let us know if you need help.

**Comment by retry19** [comment]
Is there any option to serve the project without ruby? because I check it and it's using ruby right?

**Comment by vchrombie** [comment]
> @vchrombie Is there any option to serve the project without ruby? because I check it and it's using ruby right?

umm, actually no. I am sorry but the project was built using a theme that uses ruby.
