### ISSUE TITLE
Navigation drop-down doesn't work in mobile

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-tutorial#28]
It might be a theme issue, but the navigation drop-down menu doesn't work in the mobile web. Tested in 2 Android phones, with Chrome and Firefox.

**Comment by jgbarah** [comment]
You're right, doesn't work in the tests I have done either :-(

No clue why this is happening, for now. Any hint is appreciated.

**Comment by jgbarah** [comment]
By testing in desktop, I learned that I can reproduce it if I shrink the width of the screen until the menu moves to the top of the page.

**Comment by jgbarah** [comment]
I think this is fixed now. Could we close this issue?

**Comment by jgbarah** [comment]
@jsmanrique ??

**Comment by jsmanrique** [comment]
Yes, it's working for me.
