### ISSUE TITLE
'Edit me' button doesn't link to the right address

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-tutorial#29]
It seems it misses one `/` in the template.

For example, home page `Edit me` links to:
`https://github.com/chaoss/grimoirelab-tutorial/blob/masterREADME.md` (that gives a 404 error)
Instead of:
`https://github.com/chaoss/grimoirelab-tutorial/blob/master/README.md`

**Comment by jgbarah** [comment]
It seems this only happens for the main page (README.md). For others, it seems it is working... I have to figure out why it is failing there. Thanks for the heads-up!
