### ISSUE TITLE
Link to Eclipse Development Dashboard leads to sign in page

### ISSUE THREAD

**Issue by alexcourouble** [chaoss/grimoirelab-tutorial#40]
The [Eclipse Development Dashboard](https://eclipse.biterg.io/app/kibana#/dashboard/Overview) link, which is at the end of the README requires the user to sign in in order to access the dashboard. 

Do I need to create a specific account somewhere to access the example? Or am I missing something?

**Comment by sanacl** [comment]
Hi @alexcourouble , due to some issues the Eclipse dashboard anonymous access was disabled. Recently the folks from the Eclipse foundation gave us green light to make it public again, so this will be changed during the next couple of days.

**Comment by alexcourouble** [comment]
Thanks! I'll check back again in a couple days then.
