### ISSUE TITLE
Installation: add non-Python packages needed

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-tutorial#45]
Following chaoss/grimoirelab#156, we should update the installation information with the list of non-Python packages that maybe need to be installed for the pip-based installation to work.

**Comment by vchrombie** [comment]
@jgbarah, can I take up this ?

**Comment by valeriocos** [comment]
yes @vchrombie , it would be great! thanks

**Comment by vchrombie** [comment]
So, there are two places where I need to update this. 
1. https://chaoss.github.io/grimoirelab-tutorial/basics/install.html
2. https://chaoss.github.io/grimoirelab-tutorial/basics/quick.html

@jgbarah, @valeriocos any more pages where I should be adding the information?

**Comment by valeriocos** [comment]
I don't think so!

**Comment by vchrombie** [comment]
> I don't think so!

Okay, :sweat_smile: .

I actually didn't get you. Did I mention the wrong pages or there are no extra places to add?

**Comment by valeriocos** [comment]
ehehe, you mention the right pages and there are no extra places to add.
sorry for the misunderstanding

**Comment by vchrombie** [comment]
> ehehe, you mention the right pages and there are no extra places to add.

Ok, then. :smile:
I will send a PR for the change. You can review it then.
