### ISSUE TITLE
Error while trying "Creating a simple Dashboard"

### ISSUE THREAD

**Issue by dhruv-chauhan** [chaoss/grimoirelab-tutorial#65]
Hey! 
I am a GSoC aspirant and was trying out the tutorial.

I used Docker to set the env up as mentioned here: https://chaoss.github.io/grimoirelab-tutorial/basics/quick.html#docker

I was able to do so but while trying to create indexes in ES (https://chaoss.github.io/grimoirelab-tutorial/gelk/simple.html#creating-the-indexes-in-elasticsearch), I ran into the following error, I noticed that the `git_raw` has been created but the enriched `git` index has not been.

```
2019-03-10 13:43:08,358 Error enriching ocean from git (https://github.com/grimoirelab/perceval.git): unsupported operand type(s) for +: 'bool' and 'bytes'
.
.
.
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 846, in _request_authentication
    data += self.db + b'\0'
TypeError: unsupported operand type(s) for +: 'bool' and 'bytes'
```

Full Traceback: https://pastebin.com/uHhsBnzf

NOTE: I was able to reproduce the exact same when installing via Pip and also building from current master.

Let me know if is there is something else I was supposed to do. If this is indeed an issue, I would like to take a stab at solving it.

Thanks!

**Comment by dhruv-chauhan** [comment]
@alpgarcia @mafesan, can you please take a look at this? 
Looking forward to working with you this. 

Thanks! :)

**Comment by valeriocos** [comment]
Hi @dhruv-chauhan , a similar issue was reported by @InosRahul (https://github.com/chaoss/grimoirelab-elk/issues/574). A PR has been just submitted to fix this error (https://github.com/chaoss/grimoirelab-elk/pull/576)
