### ISSUE TITLE
Error creating indexes in Docker image

### ISSUE THREAD

**Issue by satyaakam** [chaoss/grimoirelab-tutorial#73]
i was following steps from https://chaoss.github.io/grimoirelab-tutorial/gelk/simple.html in order to create indexes , i do see the index being created but its broken and lacks metadata , i see the script ending with this error https://hastebin.com/odeguyipuf.sql

**Comment by valeriocos** [comment]
Thank you for reporting this issue @satyaakam 
It seems that the version of ELK you are using it's old. Please have a look at:
https://github.com/chaoss/grimoirelab-elk/issues/574
https://github.com/chaoss/grimoirelab-manuscripts/issues/125

**Comment by satyaakam** [comment]
This worked thanks
