### ISSUE TITLE
[graal] Add Graal to GrimoireLab Tutorial

### ISSUE THREAD

**Issue by inishchith** [chaoss/grimoirelab-tutorial#75]
Current version of tutorials for set of tools provided by GrimoireLab doesn't contain tutorial for usage of [`Graal`](https://github.com/chaoss/grimoirelab-graal/). I'll be interested in adding tutorial on Graal usage to this repository.

@valeriocos @jgbarah Please do let me know what you think or if this is already being worked on.
Thanks :)

**Comment by valeriocos** [comment]
That's a good idea @inishchith . Although graal is still not integrated in the tool chain, we could start having some info in the tutorial. What do you think @jgbarah ?

**Comment by jgbarah** [comment]
Let's go for it! PR is welcome.

**Comment by inishchith** [comment]
Thanks @jgbarah @valeriocos . I'll start working on it :)

**Comment by inishchith** [comment]
Some of the tasks i feel which can be included over time:
- [ ] Include a tutorial for `CoLic` Backend ( As it requires executables of external libraries such as NOMOS & ScanCode )
- [ ] Add Graal's description to `README.md` ( once it's added to the GrimoireLab toolchain ) 

@valeriocos @jgbarah  I think this Issue should remain open for newcomers. Please do let me know what you think :)

**Comment by valeriocos** [comment]
Thank you @inishchith , I guess it's a good idea. What do you think @jgbarah ?

**Comment by jgbarah** [comment]
Yes, good idea!
