### ISSUE TITLE
[internals] Add a page regarding the use of httpretty in Perceval testing

### ISSUE THREAD

**Issue by Polaris000** [chaoss/grimoirelab-tutorial#81]
The idea was given by @valeriocos [here](https://github.com/chaoss/grimoirelab-perceval/pull/519#issuecomment-487400714). Both @harshalmittal4 and I found the process of writing tests for Perceval --- especially in the github backend --- quite difficult. 
This is an attempt at clearing things up and making it easier in the future. 

@valeriocos  recently proposed the following structure for the page (and I agree): 
- what is httpretty
- why it is useful to test perceval
- explain a test using httpretty (using one of the tests we wrote as an example)
- explain a test which combines httpretty and mock attributes (e.g., https://github.com/chaoss/grimoirelab-perceval/blob/master/tests/test_slack.py#L185)

This document will be added to the [internals folder](https://github.com/chaoss/grimoirelab-tutorial/tree/master/internals).

Let me know that you think @jgbarah, as well as anyone else who would like to get involved. :)

**Comment by jgbarah** [comment]
Please, go ahead!
