### ISSUE TITLE
[refactor] Location of image files and internals bug fix

### ISSUE THREAD

**Issue by Polaris000** [chaoss/grimoirelab-tutorial#83]
While fixing issue #57, I had n't noticed that images were present in the [assets](https://github.com/chaoss/grimoirelab-tutorial/tree/master/assets) folder. Thus, I created an [images](https://github.com/chaoss/grimoirelab-tutorial/tree/master/images) folder just to store the favicons for the site. I think it would be a great idea to move everything to one place: either to the assets folder or to the images folder.

Also, the [README](https://github.com/chaoss/grimoirelab-tutorial/blob/master/internals/README.md) in the internals folder leads to the creation of [this](https://chaoss.github.io/grimoirelab-tutorial/internals/) page when the site is generated. This causes a problem when users navigate away from this page, since the relative base url now ends with a `/internals`, leading to `page not found` errors.

I think the README should be deleted to fix this problem.

**Comment by Polaris000** [comment]
Please have a look @jgbarah, whenever covenient!

**Comment by vchrombie** [comment]
This issue is handled in the new version of the tutorial
https://github.com/chaoss/grimoirelab-tutorial/pull/178

**Comment by fioddor** [comment]
I believe this PR can be closed.

cc:@sduenas
