### ISSUE TITLE
[components] How to play with Grimoirelab components

### ISSUE THREAD

**Issue by inishchith** [chaoss/grimoirelab-tutorial#84]
As addressed in [`last meeting`](https://github.com/inishchith/gsoc-graal/blob/master/meetings/23-05-19-community-bonding.txt), I will be understanding how grimoirelab components work and propose tutorials. 
This thread works as a medium for doubts/discussion regarding the same.

@valeriocos @jgbarah Please do let me know in case I missed something out.
Thanks

**Comment by inishchith** [comment]
> An issue that I earlier faced regarding the setup of `micro-mordred` via docker-compose  is mentioned below ( REF: https://github.com/inishchith/gsoc-graal/issues/3#issuecomment-496938618 )

---------------
**`Steps`:**

1. I used the [config](https://github.com/chaoss/grimoirelab-sirmordred#source-code-and-docker) along with the mariadb service as I do not have a local setup for db.
2. executed:`docker-compose -f docker-compose.yml up`
3. executed micro in another terminal instance:`python3 micro.py --raw --enrich --cfg ./setup.cfg --backends git`
4. tried : `localhost:5601` for kibana dashboard

**`Issue`:**
- The elasticsearch instance not instantiating completely and lead the linked kibiter instance a `Request timeout after 3000ms`, leading to `localhost:5601` having no response.

- The solution that worked for me was to try adjusting the `ES_JAVA_OPTS` parameter in the *environment* attribute in the [docker config file](https://github.com/chaoss/grimoirelab-sirmordred#source-code-and-docker) for eg. ( -Xms1g -Xmx1g )
- I reached the solution via [this easticsearch forum discussion](https://discuss.elastic.co/t/kibana-request-timeout-after-3000ms/120004/3)

---------------
- After following the process, i could produce some results 🎉 

![Screenshot 2019-05-30 at 11 24 45 PM](https://user-images.githubusercontent.com/20226361/58653724-f0eac800-8333-11e9-86b7-02993881fddf.png)

<div align="center">
    <p><b>Dashboard - Git: Areas of Code </b></p>
</div>

@valeriocos @jgbarah I've worked on a tutorial for micro-mordred ( elaborating the above steps ). Let me know what you think, I may open a PR for the same. 

Thanks :)

**Comment by valeriocos** [comment]
Great, please open a PR. Don't forget to include a link to the setup.cfg and projects.json you used.

**Comment by inishchith** [comment]
@valeriocos  I've linked them and added particular notes that I faced during the process.
Please do let me know after you've had a look.

Thanks :)
