### ISSUE TITLE
Please improve the documentation about project.json in the docker page

### ISSUE THREAD

**Issue by sylvestre** [chaoss/grimoirelab-tutorial#9]
As a new user, reading the docker tutorial https://grimoirelab.gitbooks.io/tutorial/before-you-start/deploying-from-dockerhub.html
One of the first thing that I want to do is to configure my project to be analyzed.

This is probably me but I haven't been able to find the file format about the json file. I had to look to a unit test to have a clue.

The doc https://github.com/chaoss/grimoirelab/blob/master/docker/README.md has a bit more information but not enough.

**Comment by jgbarah** [comment]
I've included a new section in the tutorial: [The projects file](https://grimoirelab.gitbooks.io/tutorial/mordred/the-projects-file.html). Do you think that could be good enough?

**Comment by Polaris000** [comment]
Hey @sylvestre, thanks for raising this query!
 I know its been a long time but does this change help? 
Let us know so one of the maintainers can close this issue.
Thanks!

**Comment by sylvestre** [comment]
yeah, we can probably close it, thanks :)

**Comment by Polaris000** [comment]
Great, thanks for the prompt response!
