### ISSUE TITLE
Update doc to handle git private repos

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-tutorial#95]
As reported https://github.com/chaoss/grimoirelab/issues/205, the procedure to analyze private git repository is not described in the tutorial. Probably the doc could be improved to add a short description about these cases. In particular the private git repos should be declared in the projects.json with the following shape:
```
"git": [
            "https://<username-github>:<api-token>@github.com/org/repo"
        ],
```

**Comment by vchrombie** [comment]
This issue was addressed in the new tutorial https://github.com/chaoss/grimoirelab-tutorial/pull/173
The information and example is added to the sirmordred repository too https://github.com/chaoss/grimoirelab-sirmordred/pull/519

Closing the issue as it is resolved now.
